### ISSUE TITLE
CUDA Out Of Memory Error on consecutive inferences

### ISSUE THREAD

**Issue by ThrowawayAccount01** [voicepaw/so-vits-svc-fork#476]
Fresh install on 3.11.0, when doing normal inference, the first attempt was successful. However, on the 2nd attempt, it gives a OOM error:

```
(venv) C:\Users\LXC PC\Desktop\sovitsfresh\venv\Scripts>svcg
[11:15:14] INFO     [11:15:14] version: 3.11.0                                                                gui.py:144
[11:15:30] INFO     [11:15:30] Event model_path, values {'model_path': 'C:/Users/LXC                          gui.py:568
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'model_path_browse': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'config_path': '',
                    'config_path_browse': '', 'cluster_model_path': '', 'cluster_model_path_browse': '',
                    'speaker': '', 'silence_threshold': -35.0, 'transpose': 12.0, 'auto_predict_f0': False,
                    'f0_method': 'dio', 'cluster_infer_ratio': 0.0, 'noise_scale': 0.4, 'pad_seconds': 0.1,
                    'chunk_seconds': 0.5, 'absolute_thresh': True, 'input_path': '', 'input_path_browse': '',
                    'output_path': '', 'output_path_browse': '', 'auto_play': True, 'crossfade_seconds':
                    0.05, 'block_seconds': 0.35, 'additional_infer_before_seconds': 0.15,
                    'additional_infer_after_seconds': 0.1, 'realtime_algorithm': '1 (Divide constantly)',
                    'input_device': 'Microphone (SplitCam Audio Mixe (MME)', 'output_device': 'Realtek HD
                    Audio 2nd output (Re (MME)', 'passthrough_original': False, 'presets': 'Default VC (GPU,
                    GTX 1060)', 'preset_name': '', 'use_gpu': True}
           INFO     [11:15:30] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199D0999F10> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3\300
           INFO     [11:15:30] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F0FF1790> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3\300
           INFO     [11:15:30] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F696D310> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3\300
           INFO     [11:15:30] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F6990190> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3\300
           INFO     [11:15:30] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F69904F0> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3\300
[11:15:33] INFO     [11:15:33] Event config_path, values {'model_path': 'C:/Users/LXC                         gui.py:568
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'model_path_browse': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'config_path': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/config.json', 'config_path_browse': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/config.json', 'cluster_model_path': '',
                    'cluster_model_path_browse': '', 'speaker': '', 'silence_threshold': -35.0, 'transpose':
                    12.0, 'auto_predict_f0': False, 'f0_method': 'dio', 'cluster_infer_ratio': 0.0,
                    'noise_scale': 0.4, 'pad_seconds': 0.1, 'chunk_seconds': 0.5, 'absolute_thresh': True,
                    'input_path': '', 'input_path_browse': '', 'output_path': '', 'output_path_browse': '',
                    'auto_play': True, 'crossfade_seconds': 0.05, 'block_seconds': 0.35,
                    'additional_infer_before_seconds': 0.15, 'additional_infer_after_seconds': 0.1,
                    'realtime_algorithm': '1 (Divide constantly)', 'input_device': 'Microphone (SplitCam
                    Audio Mixe (MME)', 'output_device': 'Realtek HD Audio 2nd output (Re (MME)',
                    'passthrough_original': False, 'presets': 'Default VC (GPU, GTX 1060)', 'preset_name':
                    '', 'use_gpu': True}
           INFO     [11:15:33] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199D0999F10> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3
           INFO     [11:15:33] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F0FF1790> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3
           INFO     [11:15:33] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F696D310> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3
           INFO     [11:15:33] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F6990190> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3
           INFO     [11:15:33] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F69904F0> gui.py:574
                    to C:\Users\LXC PC\Desktop\BackupTraining\sovits\nyuv3
[11:15:58] INFO     [11:15:58] Event input_path, values {'model_path': 'C:/Users/LXC                          gui.py:568
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'model_path_browse': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'config_path': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/config.json', 'config_path_browse': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/config.json', 'cluster_model_path': '',
                    'cluster_model_path_browse': '', 'speaker': 'nyuv3', 'silence_threshold': -35.0,
                    'transpose': -6.0, 'auto_predict_f0': False, 'f0_method': 'crepe', 'cluster_infer_ratio':
                    0.0, 'noise_scale': 0.4, 'pad_seconds': 0.1, 'chunk_seconds': 0.5, 'absolute_thresh':
                    True, 'input_path': 'C:/Users/LXC
                    PC/Desktop/sovitsinout/oshi/split/1_oshiraw_(Vocals).wav', 'input_path_browse':
                    'C:/Users/LXC PC/Desktop/sovitsinout/oshi/split/1_oshiraw_(Vocals).wav', 'output_path':
                    '', 'output_path_browse': '', 'auto_play': True, 'crossfade_seconds': 0.05,
                    'block_seconds': 0.35, 'additional_infer_before_seconds': 0.15,
                    'additional_infer_after_seconds': 0.1, 'realtime_algorithm': '1 (Divide constantly)',
                    'input_device': 'Microphone (SplitCam Audio Mixe (MME)', 'output_device': 'Realtek HD
                    Audio 2nd output (Re (MME)', 'passthrough_original': False, 'presets': 'Default VC (GPU,
                    GTX 1060)', 'preset_name': '', 'use_gpu': True}
           INFO     [11:15:58] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199D0999F10> gui.py:574
                    to C:\Users\LXC PC\Desktop\sovitsinout\oshi\split
           INFO     [11:15:58] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F0FF1790> gui.py:574
                    to C:\Users\LXC PC\Desktop\sovitsinout\oshi\split
           INFO     [11:15:58] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F696D310> gui.py:574
                    to C:\Users\LXC PC\Desktop\sovitsinout\oshi\split
           INFO     [11:15:58] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F6990190> gui.py:574
                    to C:\Users\LXC PC\Desktop\sovitsinout\oshi\split
           INFO     [11:15:58] Updating browser <PySimpleGUI.PySimpleGUI.Button object at 0x00000199F69904F0> gui.py:574
                    to C:\Users\LXC PC\Desktop\sovitsinout\oshi\split
[11:16:04] INFO     [11:16:04] Event infer, values {'model_path': 'C:/Users/LXC                               gui.py:568
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'model_path_browse': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'config_path': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/config.json', 'config_path_browse': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/config.json', 'cluster_model_path': '',
                    'cluster_model_path_browse': '', 'speaker': 'nyuv3', 'silence_threshold': -35.0,
                    'transpose': -6.0, 'auto_predict_f0': False, 'f0_method': 'crepe', 'cluster_infer_ratio':
                    0.0, 'noise_scale': 0.4, 'pad_seconds': 0.1, 'chunk_seconds': 0.5, 'absolute_thresh':
                    True, 'input_path': 'C:/Users/LXC
                    PC/Desktop/sovitsinout/oshi/split/1_oshiraw_(Vocals).wav', 'input_path_browse':
                    'C:/Users/LXC PC/Desktop/sovitsinout/oshi/split/1_oshiraw_(Vocals).wav', 'output_path':
                    'C:\\Users\\LXC PC\\Desktop\\sovitsinout\\oshi\\split\\1_oshiraw_(Vocals).out.wav',
                    'output_path_browse': '', 'auto_play': False, 'crossfade_seconds': 0.05, 'block_seconds':
                    0.35, 'additional_infer_before_seconds': 0.15, 'additional_infer_after_seconds': 0.1,
                    'realtime_algorithm': '1 (Divide constantly)', 'input_device': 'Microphone (SplitCam
                    Audio Mixe (MME)', 'output_device': 'Realtek HD Audio 2nd output (Re (MME)',
                    'passthrough_original': False, 'presets': 'Default VC (GPU, GTX 1060)', 'preset_name':
                    '', 'use_gpu': True}
[11:16:05] INFO     [11:16:05] Starting inference...                                                          gui.py:620
[11:16:08] WARNING  [11:16:08] C:\Users\LXC                                                              warnings.py:109
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\synthesizers.
                    py:81: UserWarning: Unused arguments: {'n_layers_q': 3, 'use_spectral_norm': False}
                      warnings.warn(f"Unused arguments: {kwargs}")

           INFO     [11:16:08] Decoder type: hifi-gan                                                synthesizers.py:100
[11:16:09] INFO     [11:16:09] Loaded checkpoint 'C:/Users/LXC                                              utils.py:259
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth' (iteration 300)
           INFO     [11:16:09] Chunk: Chunk(Speech: False, 26460.0)                                          core.py:271
           INFO     [11:16:09] Chunk: Chunk(Speech: True, 617400.0)                                          core.py:271
[11:16:15] INFO     [11:16:15] F0 inference time:       5.868s, RTF: 0.413                                     f0.py:214
           WARNING  [11:16:15] C:\Users\LXC                                                              warnings.py:109
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\utils.py:177:
                    UserWarning: legacy_final_proj is deprecated
                      warnings.warn("legacy_final_proj is deprecated")

           INFO     [11:16:15] HuBERT inference time  : 0.033s, RTF: 0.002                                  utils.py:186
[11:16:16] INFO     [11:16:16] Inferece time: 0.68s, RTF: 0.05                                               core.py:227
           INFO     [11:16:16] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:16] Chunk: Chunk(Speech: True, 2804760.0)                                         core.py:271
[11:16:20] INFO     [11:16:20] F0 inference time:       4.027s, RTF: 0.063                                     f0.py:214
           INFO     [11:16:20] HuBERT inference time  : 0.026s, RTF: 0.000                                  utils.py:186
[11:16:21] INFO     [11:16:21] Inferece time: 0.46s, RTF: 0.01                                               core.py:227
[11:16:23] INFO     [11:16:23] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:23] Chunk: Chunk(Speech: True, 3175200.0)                                         core.py:271
[11:16:28] INFO     [11:16:28] F0 inference time:       4.590s, RTF: 0.064                                     f0.py:214
           INFO     [11:16:28] HuBERT inference time  : 0.025s, RTF: 0.000                                  utils.py:186
[11:16:29] INFO     [11:16:29] Inferece time: 1.27s, RTF: 0.02                                               core.py:227
[11:16:31] INFO     [11:16:31] Chunk: Chunk(Speech: False, 26460.0)                                          core.py:271
           INFO     [11:16:31] Chunk: Chunk(Speech: True, 1896300.0)                                         core.py:271
[11:16:34] INFO     [11:16:34] F0 inference time:       3.139s, RTF: 0.073                                     f0.py:214
           INFO     [11:16:34] HuBERT inference time  : 0.031s, RTF: 0.001                                  utils.py:186
[11:16:35] INFO     [11:16:35] Inferece time: 0.29s, RTF: 0.01                                               core.py:227
[11:16:36] INFO     [11:16:36] Chunk: Chunk(Speech: False, 26460.0)                                          core.py:271
           INFO     [11:16:36] Chunk: Chunk(Speech: True, 17640.0)                                           core.py:271
           INFO     [11:16:36] F0 inference time:       0.055s, RTF: 0.091                                     f0.py:214
           INFO     [11:16:36] HuBERT inference time  : 0.027s, RTF: 0.045                                  utils.py:186
           INFO     [11:16:36] Inferece time: 0.18s, RTF: 0.31                                               core.py:227
           INFO     [11:16:36] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:36] Chunk: Chunk(Speech: True, 26460.0)                                           core.py:271
           INFO     [11:16:36] F0 inference time:       0.072s, RTF: 0.090                                     f0.py:214
[11:16:37] INFO     [11:16:37] HuBERT inference time  : 0.025s, RTF: 0.032                                  utils.py:186
           INFO     [11:16:37] Inferece time: 0.17s, RTF: 0.21                                               core.py:227
           INFO     [11:16:37] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:37] Chunk: Chunk(Speech: True, 26460.0)                                           core.py:271
           INFO     [11:16:37] F0 inference time:       0.063s, RTF: 0.079                                     f0.py:214
           INFO     [11:16:37] HuBERT inference time  : 0.008s, RTF: 0.010                                  utils.py:186
           INFO     [11:16:37] Inferece time: 0.03s, RTF: 0.04                                               core.py:227
           INFO     [11:16:37] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:37] Chunk: Chunk(Speech: True, 17640.0)                                           core.py:271
           INFO     [11:16:37] F0 inference time:       0.057s, RTF: 0.095                                     f0.py:214
           INFO     [11:16:37] HuBERT inference time  : 0.008s, RTF: 0.014                                  utils.py:186
           INFO     [11:16:37] Inferece time: 0.03s, RTF: 0.05                                               core.py:227
           INFO     [11:16:37] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:37] Chunk: Chunk(Speech: True, 26460.0)                                           core.py:271
           INFO     [11:16:37] F0 inference time:       0.073s, RTF: 0.091                                     f0.py:214
           INFO     [11:16:37] HuBERT inference time  : 0.007s, RTF: 0.009                                  utils.py:186
           INFO     [11:16:37] Inferece time: 0.03s, RTF: 0.04                                               core.py:227
           INFO     [11:16:37] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:37] Chunk: Chunk(Speech: True, 17640.0)                                           core.py:271
           INFO     [11:16:37] F0 inference time:       0.058s, RTF: 0.096                                     f0.py:214
           INFO     [11:16:37] HuBERT inference time  : 0.008s, RTF: 0.014                                  utils.py:186
           INFO     [11:16:37] Inferece time: 0.03s, RTF: 0.05                                               core.py:227
           INFO     [11:16:37] Chunk: Chunk(Speech: False, 17640.0)                                          core.py:271
           INFO     [11:16:37] Chunk: Chunk(Speech: True, 52920.0)                                           core.py:271
           INFO     [11:16:37] F0 inference time:       0.110s, RTF: 0.079                                     f0.py:214
           INFO     [11:16:37] HuBERT inference time  : 0.029s, RTF: 0.021                                  utils.py:186
[11:16:38] INFO     [11:16:38] Inferece time: 0.17s, RTF: 0.13                                               core.py:227
           INFO     [11:16:38] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:38] Chunk: Chunk(Speech: True, 52920.0)                                           core.py:271
           INFO     [11:16:38] F0 inference time:       0.101s, RTF: 0.072                                     f0.py:214
           INFO     [11:16:38] HuBERT inference time  : 0.008s, RTF: 0.006                                  utils.py:186
           INFO     [11:16:38] Inferece time: 0.03s, RTF: 0.02                                               core.py:227
           INFO     [11:16:38] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:38] Chunk: Chunk(Speech: True, 17640.0)                                           core.py:271
           INFO     [11:16:38] F0 inference time:       0.055s, RTF: 0.092                                     f0.py:214
           INFO     [11:16:38] HuBERT inference time  : 0.010s, RTF: 0.016                                  utils.py:186
           INFO     [11:16:38] Inferece time: 0.03s, RTF: 0.05                                               core.py:227
           INFO     [11:16:38] Chunk: Chunk(Speech: False, 17640.0)                                          core.py:271
           INFO     [11:16:38] Chunk: Chunk(Speech: True, 17640.0)                                           core.py:271
           INFO     [11:16:38] F0 inference time:       0.058s, RTF: 0.097                                     f0.py:214
           INFO     [11:16:38] HuBERT inference time  : 0.008s, RTF: 0.013                                  utils.py:186
           INFO     [11:16:38] Inferece time: 0.03s, RTF: 0.05                                               core.py:227
           INFO     [11:16:38] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:38] Chunk: Chunk(Speech: True, 26460.0)                                           core.py:271
           INFO     [11:16:38] F0 inference time:       0.070s, RTF: 0.088                                     f0.py:214
           INFO     [11:16:38] HuBERT inference time  : 0.008s, RTF: 0.010                                  utils.py:186
           INFO     [11:16:38] Inferece time: 0.03s, RTF: 0.04                                               core.py:227
           INFO     [11:16:38] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:38] Chunk: Chunk(Speech: True, 17640.0)                                           core.py:271
           INFO     [11:16:38] F0 inference time:       0.059s, RTF: 0.098                                     f0.py:214
           INFO     [11:16:38] HuBERT inference time  : 0.010s, RTF: 0.016                                  utils.py:186
           INFO     [11:16:38] Inferece time: 0.03s, RTF: 0.05                                               core.py:227
           INFO     [11:16:38] Chunk: Chunk(Speech: False, 17640.0)                                          core.py:271
           INFO     [11:16:38] Chunk: Chunk(Speech: True, 17640.0)                                           core.py:271
           INFO     [11:16:38] F0 inference time:       0.057s, RTF: 0.094                                     f0.py:214
           INFO     [11:16:38] HuBERT inference time  : 0.011s, RTF: 0.018                                  utils.py:186
           INFO     [11:16:38] Inferece time: 0.03s, RTF: 0.05                                               core.py:227
           INFO     [11:16:38] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:38] Chunk: Chunk(Speech: True, 220500.0)                                          core.py:271
[11:16:39] INFO     [11:16:39] F0 inference time:       0.352s, RTF: 0.068                                     f0.py:214
           INFO     [11:16:39] HuBERT inference time  : 0.028s, RTF: 0.005                                  utils.py:186
           INFO     [11:16:39] Inferece time: 0.17s, RTF: 0.03                                               core.py:227
           INFO     [11:16:39] Chunk: Chunk(Speech: False, 668892.0)                                         core.py:271
[11:16:39] INFO     [11:16:39] Finished inference for 1_oshiraw_(Vocals).wav                                  gui.py:134
[11:16:56] INFO     [11:16:56] Event infer, values {'model_path': 'C:/Users/LXC                               gui.py:568
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'model_path_browse': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth', 'config_path': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/config.json', 'config_path_browse': 'C:/Users/LXC
                    PC/Desktop/BackupTraining/sovits/nyuv3/config.json', 'cluster_model_path': '',
                    'cluster_model_path_browse': '', 'speaker': 'nyuv3', 'silence_threshold': -35.0,
                    'transpose': -8.0, 'auto_predict_f0': False, 'f0_method': 'crepe', 'cluster_infer_ratio':
                    0.0, 'noise_scale': 0.4, 'pad_seconds': 0.1, 'chunk_seconds': 0.5, 'absolute_thresh':
                    True, 'input_path': 'C:/Users/LXC
                    PC/Desktop/sovitsinout/oshi/split/1_oshiraw_(Vocals).wav', 'input_path_browse':
                    'C:/Users/LXC PC/Desktop/sovitsinout/oshi/split/1_oshiraw_(Vocals).wav', 'output_path':
                    'C:\\Users\\LXC PC\\Desktop\\sovitsinout\\oshi\\split\\1_oshiraw_(Vocals).out.wav',
                    'output_path_browse': '', 'auto_play': False, 'crossfade_seconds': 0.05, 'block_seconds':
                    0.35, 'additional_infer_before_seconds': 0.15, 'additional_infer_after_seconds': 0.1,
                    'realtime_algorithm': '1 (Divide constantly)', 'input_device': 'Microphone (SplitCam
                    Audio Mixe (MME)', 'output_device': 'Realtek HD Audio 2nd output (Re (MME)',
                    'passthrough_original': False, 'presets': 'Default VC (GPU, GTX 1060)', 'preset_name':
                    '', 'use_gpu': True}
           INFO     [11:16:56] Starting inference...                                                          gui.py:620
[11:16:57] WARNING  [11:16:57] C:\Users\LXC                                                              warnings.py:109
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\synthesizers.
                    py:81: UserWarning: Unused arguments: {'n_layers_q': 3, 'use_spectral_norm': False}
                      warnings.warn(f"Unused arguments: {kwargs}")

           INFO     [11:16:57] Decoder type: hifi-gan                                                synthesizers.py:100
           INFO     [11:16:57] Loaded checkpoint 'C:/Users/LXC                                              utils.py:259
                    PC/Desktop/BackupTraining/sovits/nyuv3/300/G_300.pth' (iteration 300)
[11:16:58] INFO     [11:16:58] Chunk: Chunk(Speech: False, 26460.0)                                          core.py:271
           INFO     [11:16:58] Chunk: Chunk(Speech: True, 617400.0)                                          core.py:271
[11:16:59] INFO     [11:16:59] F0 inference time:       0.943s, RTF: 0.066                                     f0.py:214
           WARNING  [11:16:59] C:\Users\LXC                                                              warnings.py:109
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\utils.py:177:
                    UserWarning: legacy_final_proj is deprecated
                      warnings.warn("legacy_final_proj is deprecated")

           INFO     [11:16:59] HuBERT inference time  : 0.010s, RTF: 0.001                                  utils.py:186
           INFO     [11:16:59] Inferece time: 0.06s, RTF: 0.00                                               core.py:227
           INFO     [11:16:59] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:16:59] Chunk: Chunk(Speech: True, 2804760.0)                                         core.py:271
[11:17:03] INFO     [11:17:03] F0 inference time:       4.070s, RTF: 0.064                                     f0.py:214
           INFO     [11:17:03] HuBERT inference time  : 0.008s, RTF: 0.000                                  utils.py:186
[11:17:04] INFO     [11:17:04] Inferece time: 0.38s, RTF: 0.01                                               core.py:227
[11:17:06] INFO     [11:17:06] Chunk: Chunk(Speech: False, 8820.0)                                           core.py:271
           INFO     [11:17:06] Chunk: Chunk(Speech: True, 3175200.0)                                         core.py:271
[11:17:11] INFO     [11:17:11] F0 inference time:       4.751s, RTF: 0.066                                     f0.py:214
           INFO     [11:17:11] HuBERT inference time  : 0.008s, RTF: 0.000                                  utils.py:186
[11:17:11] INFO     [11:17:11] Finished inference for 1_oshiraw_(Vocals).wav                                  gui.py:134
           ERROR    [11:17:11] Error in realtime:                                                             gui.py:731
           ERROR    [11:17:11] CUDA out of memory. Tried to allocate 590.00 MiB (GPU 0; 8.00 GiB total        gui.py:732
                    capacity; 4.88 GiB already allocated; 0 bytes free; 7.04 GiB reserved in total by
                    PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid
                    fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File "C:\Users\LXC PC\Desktop\sovitsfresh\venv\lib\site-packages\pebble\common.py",
                    line 174, in process_execute
                        return function(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\inference\main.py", line
                    56, in infer
                        audio = svc_model.infer_silence(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\inference\core.py", line
                    284, in infer_silence
                        audio_chunk_pad_infer_tensor, _ = self.infer(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\inference\core.py", line
                    218, in infer
                        audio = self.net_g.infer(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\synthesizers.py",
                    line 223, in infer
                        z_p, m_p, logs_p, c_mask = self.enc_p(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in
                    _call_impl
                        return forward_call(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\encoders.py", line
                    131, in forward
                        x = self.enc_(x * x_mask, x_mask)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in
                    _call_impl
                        return forward_call(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 136, in forward
                        y = self.attn_layers[i](x, x, attn_mask)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in
                    _call_impl
                        return forward_call(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 292, in forward
                        x, self.attn = self.attention(q, k, v, mask=attn_mask)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 336, in attention
                        relative_weights = self._absolute_position_to_relative_position(p_attn)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 417, in _absolute_position_to_relative_position
                        x_flat = F.pad(x_flat, commons.convert_pad_shape([[0, 0], [0, 0], [length, 0]]))
                    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 590.00 MiB (GPU 0;
                    8.00 GiB total capacity; 4.88 GiB already allocated; 0 bytes free; 7.04 GiB reserved in
                    total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb
                    to avoid fragmentation.  See documentation for Memory Management and
                    PYTORCH_CUDA_ALLOC_CONF


                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 729, in main
                        future.result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 439, in result
                        return self.__get_result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 391, in
                    __get_result
                        raise self._exception
                    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 590.00 MiB (GPU 0;
                    8.00 GiB total capacity; 4.88 GiB already allocated; 0 bytes free; 7.04 GiB reserved in
                    total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb
                    to avoid fragmentation.  See documentation for Memory Management and
                    PYTORCH_CUDA_ALLOC_CONF
           ERROR    [11:17:11] Error in inference:                                                            gui.py:739
           ERROR    [11:17:11] CUDA out of memory. Tried to allocate 590.00 MiB (GPU 0; 8.00 GiB total        gui.py:740
                    capacity; 4.88 GiB already allocated; 0 bytes free; 7.04 GiB reserved in total by
                    PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid
                    fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File "C:\Users\LXC PC\Desktop\sovitsfresh\venv\lib\site-packages\pebble\common.py",
                    line 174, in process_execute
                        return function(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\inference\main.py", line
                    56, in infer
                        audio = svc_model.infer_silence(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\inference\core.py", line
                    284, in infer_silence
                        audio_chunk_pad_infer_tensor, _ = self.infer(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\inference\core.py", line
                    218, in infer
                        audio = self.net_g.infer(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\synthesizers.py",
                    line 223, in infer
                        z_p, m_p, logs_p, c_mask = self.enc_p(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in
                    _call_impl
                        return forward_call(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\encoders.py", line
                    131, in forward
                        x = self.enc_(x * x_mask, x_mask)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in
                    _call_impl
                        return forward_call(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 136, in forward
                        y = self.attn_layers[i](x, x, attn_mask)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in
                    _call_impl
                        return forward_call(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 292, in forward
                        x, self.attn = self.attention(q, k, v, mask=attn_mask)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 336, in attention
                        relative_weights = self._absolute_position_to_relative_position(p_attn)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 417, in _absolute_position_to_relative_position
                        x_flat = F.pad(x_flat, commons.convert_pad_shape([[0, 0], [0, 0], [length, 0]]))
                    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 590.00 MiB (GPU 0;
                    8.00 GiB total capacity; 4.88 GiB already allocated; 0 bytes free; 7.04 GiB reserved in
                    total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb
                    to avoid fragmentation.  See documentation for Memory Management and
                    PYTORCH_CUDA_ALLOC_CONF


                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 737, in main
                        future.result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 439, in result
                        return self.__get_result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 391, in
                    __get_result
                        raise self._exception
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 729, in main
                        future.result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 439, in result
                        return self.__get_result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 391, in
                    __get_result
                        raise self._exception
                    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 590.00 MiB (GPU 0;
                    8.00 GiB total capacity; 4.88 GiB already allocated; 0 bytes free; 7.04 GiB reserved in
                    total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb
                    to avoid fragmentation.  See documentation for Memory Management and
                    PYTORCH_CUDA_ALLOC_CONF
[11:17:12] ERROR    [11:17:12] Error in realtime:                                                             gui.py:731
           ERROR    [11:17:12] CUDA out of memory. Tried to allocate 590.00 MiB (GPU 0; 8.00 GiB total        gui.py:732
                    capacity; 4.88 GiB already allocated; 0 bytes free; 7.04 GiB reserved in total by
                    PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid
                    fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
                    pebble.common.RemoteTraceback: Traceback (most recent call last):
                      File "C:\Users\LXC PC\Desktop\sovitsfresh\venv\lib\site-packages\pebble\common.py",
                    line 174, in process_execute
                        return function(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\inference\main.py", line
                    56, in infer
                        audio = svc_model.infer_silence(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\inference\core.py", line
                    284, in infer_silence
                        audio_chunk_pad_infer_tensor, _ = self.infer(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\inference\core.py", line
                    218, in infer
                        audio = self.net_g.infer(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\synthesizers.py",
                    line 223, in infer
                        z_p, m_p, logs_p, c_mask = self.enc_p(
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in
                    _call_impl
                        return forward_call(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\encoders.py", line
                    131, in forward
                        x = self.enc_(x * x_mask, x_mask)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in
                    _call_impl
                        return forward_call(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 136, in forward
                        y = self.attn_layers[i](x, x, attn_mask)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in
                    _call_impl
                        return forward_call(*args, **kwargs)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 292, in forward
                        x, self.attn = self.attention(q, k, v, mask=attn_mask)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 336, in attention
                        relative_weights = self._absolute_position_to_relative_position(p_attn)
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\modules\attentions.py",
                    line 417, in _absolute_position_to_relative_position
                        x_flat = F.pad(x_flat, commons.convert_pad_shape([[0, 0], [0, 0], [length, 0]]))
                    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 590.00 MiB (GPU 0;
                    8.00 GiB total capacity; 4.88 GiB already allocated; 0 bytes free; 7.04 GiB reserved in
                    total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb
                    to avoid fragmentation.  See documentation for Memory Management and
                    PYTORCH_CUDA_ALLOC_CONF


                    The above exception was the direct cause of the following exception:

                    Traceback (most recent call last):
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 729, in main
                        future.result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 439, in result
                        return self.__get_result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 391, in
                    __get_result
                        raise self._exception
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 737, in main
                        future.result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 439, in result
                        return self.__get_result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 391, in
                    __get_result
                        raise self._exception
                      File "C:\Users\LXC
                    PC\Desktop\sovitsfresh\venv\lib\site-packages\so_vits_svc_fork\gui.py", line 729, in main
                        future.result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 439, in result
                        return self.__get_result()
                      File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 391, in
                    __get_result
                        raise self._exception
                    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 590.00 MiB (GPU 0;
                    8.00 GiB total capacity; 4.88 GiB already allocated; 0 bytes free; 7.04 GiB reserved in
                    total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb
                    to avoid fragmentation.  See documentation for Memory Management and
                    PYTORCH_CUDA_ALLOC_CONF
```

Looking at the task manager, it seems that the System RAM and GPU VRAM used is not being released after inference?

![gpu](https://user-images.githubusercontent.com/125531852/233892753-5237efb1-7d47-4f6d-8f23-779586cefcb6.png)

**Comment by QuLOVE** [comment]
on the latest version the same problem btw.
gtx 1650ti 4gb (laptop gpu)

on the 3.10.4 wasnt any problems with inference longer than 5 min. now at the latest version i cant infer with 30 sec audio and getting OOM.

**Comment by iRadioMan** [comment]
Decrease the "batch_size" value in config.json until it starts to work properly

**Comment by krzysiek546** [comment]
> Decrease the "batch_size" value in config.json until it starts to work properly

So, does this mean that the batch_size set during training in the config.json file can have a later impact on inference?

**Comment by iRadioMan** [comment]
> So, does this mean that the batch_size set during training in the config.json file can have a later impact on inference?

Maybe, but I didn't notice much difference. I'd rather have it that way than not working at all. 

I think about buying a GPU with more VRAM in the future :>

**Comment by hklchung** [comment]
I am taking a guess here. I noticed that when feeding in audio clips for inferencing, if the audio clip has distinct pauses/silence in between talking/singing, it knows where to split the audio into smaller chunks for the inference step. When the audio does not have distinct pauses/silence in between talking/singing, it will try to inference the full audio clip in one go, and thats when you would run into the CUDA OOM error. The solution is to write a loop to inference each 10 second segment one by one.

**Comment by bio-mlhui** [comment]
i set  **os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'max_split_size_mb:4096' according to ** https://blog.csdn.net/MirageTanker/article/details/127998036. and it works

**Comment by VioletElysia** [comment]
> i set **os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'max_split_size_mb:4096' according to** https://blog.csdn.net/MirageTanker/article/details/127998036. and it works
> 
> a smaller value, like 1024, is better

Hello, please ask in which file you are configuring
set PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024
What about this passage
